#ifndef HYPERION_REPLY_READER_H
#define HYPERION_REPLY_READER_H

/* Generated by flatcc 0.6.0 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct hyperionnet_Reply_table *hyperionnet_Reply_table_t;
typedef struct hyperionnet_Reply_table *hyperionnet_Reply_mutable_table_t;
typedef const flatbuffers_uoffset_t *hyperionnet_Reply_vec_t;
typedef flatbuffers_uoffset_t *hyperionnet_Reply_mutable_vec_t;
#ifndef hyperionnet_Reply_identifier
#define hyperionnet_Reply_identifier flatbuffers_identifier
#endif
#define hyperionnet_Reply_type_hash ((flatbuffers_thash_t)0x39df98ba)
#define hyperionnet_Reply_type_identifier "\xba\x98\xdf\x39"



struct hyperionnet_Reply_table { uint8_t unused__; };

static inline size_t hyperionnet_Reply_vec_len(hyperionnet_Reply_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hyperionnet_Reply_table_t hyperionnet_Reply_vec_at(hyperionnet_Reply_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hyperionnet_Reply_table_t, vec, i, 0)
__flatbuffers_table_as_root(hyperionnet_Reply)

__flatbuffers_define_string_field(0, hyperionnet_Reply, error, 0)
__flatbuffers_define_scalar_field(1, hyperionnet_Reply, video, flatbuffers_int32, int32_t, INT32_C(-1))
__flatbuffers_define_scalar_field(2, hyperionnet_Reply, registered, flatbuffers_int32, int32_t, INT32_C(-1))


#include "flatcc/flatcc_epilogue.h"
#endif /* HYPERION_REPLY_READER_H */
