#ifndef HYPERION_REQUEST_READER_H
#define HYPERION_REQUEST_READER_H

/* Generated by flatcc 0.6.0 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct hyperionnet_Register_table *hyperionnet_Register_table_t;
typedef struct hyperionnet_Register_table *hyperionnet_Register_mutable_table_t;
typedef const flatbuffers_uoffset_t *hyperionnet_Register_vec_t;
typedef flatbuffers_uoffset_t *hyperionnet_Register_mutable_vec_t;
typedef const struct hyperionnet_RawImage_table *hyperionnet_RawImage_table_t;
typedef struct hyperionnet_RawImage_table *hyperionnet_RawImage_mutable_table_t;
typedef const flatbuffers_uoffset_t *hyperionnet_RawImage_vec_t;
typedef flatbuffers_uoffset_t *hyperionnet_RawImage_mutable_vec_t;
typedef const struct hyperionnet_Image_table *hyperionnet_Image_table_t;
typedef struct hyperionnet_Image_table *hyperionnet_Image_mutable_table_t;
typedef const flatbuffers_uoffset_t *hyperionnet_Image_vec_t;
typedef flatbuffers_uoffset_t *hyperionnet_Image_mutable_vec_t;
typedef const struct hyperionnet_Clear_table *hyperionnet_Clear_table_t;
typedef struct hyperionnet_Clear_table *hyperionnet_Clear_mutable_table_t;
typedef const flatbuffers_uoffset_t *hyperionnet_Clear_vec_t;
typedef flatbuffers_uoffset_t *hyperionnet_Clear_mutable_vec_t;
typedef const struct hyperionnet_Color_table *hyperionnet_Color_table_t;
typedef struct hyperionnet_Color_table *hyperionnet_Color_mutable_table_t;
typedef const flatbuffers_uoffset_t *hyperionnet_Color_vec_t;
typedef flatbuffers_uoffset_t *hyperionnet_Color_mutable_vec_t;
typedef const struct hyperionnet_Request_table *hyperionnet_Request_table_t;
typedef struct hyperionnet_Request_table *hyperionnet_Request_mutable_table_t;
typedef const flatbuffers_uoffset_t *hyperionnet_Request_vec_t;
typedef flatbuffers_uoffset_t *hyperionnet_Request_mutable_vec_t;
#ifndef hyperionnet_Register_identifier
#define hyperionnet_Register_identifier flatbuffers_identifier
#endif
#define hyperionnet_Register_type_hash ((flatbuffers_thash_t)0x7c76c8af)
#define hyperionnet_Register_type_identifier "\xaf\xc8\x76\x7c"
#ifndef hyperionnet_RawImage_identifier
#define hyperionnet_RawImage_identifier flatbuffers_identifier
#endif
#define hyperionnet_RawImage_type_hash ((flatbuffers_thash_t)0xe4f6f14d)
#define hyperionnet_RawImage_type_identifier "\x4d\xf1\xf6\xe4"
#ifndef hyperionnet_Image_identifier
#define hyperionnet_Image_identifier flatbuffers_identifier
#endif
#define hyperionnet_Image_type_hash ((flatbuffers_thash_t)0x947b2cb)
#define hyperionnet_Image_type_identifier "\xcb\xb2\x47\x09"
#ifndef hyperionnet_Clear_identifier
#define hyperionnet_Clear_identifier flatbuffers_identifier
#endif
#define hyperionnet_Clear_type_hash ((flatbuffers_thash_t)0x2ef9ebb7)
#define hyperionnet_Clear_type_identifier "\xb7\xeb\xf9\x2e"
#ifndef hyperionnet_Color_identifier
#define hyperionnet_Color_identifier flatbuffers_identifier
#endif
#define hyperionnet_Color_type_hash ((flatbuffers_thash_t)0x30986e49)
#define hyperionnet_Color_type_identifier "\x49\x6e\x98\x30"
#ifndef hyperionnet_Request_identifier
#define hyperionnet_Request_identifier flatbuffers_identifier
#endif
#define hyperionnet_Request_type_hash ((flatbuffers_thash_t)0x5aeb78cb)
#define hyperionnet_Request_type_identifier "\xcb\x78\xeb\x5a"



struct hyperionnet_Register_table { uint8_t unused__; };

static inline size_t hyperionnet_Register_vec_len(hyperionnet_Register_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hyperionnet_Register_table_t hyperionnet_Register_vec_at(hyperionnet_Register_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hyperionnet_Register_table_t, vec, i, 0)
__flatbuffers_table_as_root(hyperionnet_Register)

__flatbuffers_define_string_field(0, hyperionnet_Register, origin, 1)
__flatbuffers_define_scalar_field(1, hyperionnet_Register, priority, flatbuffers_int32, int32_t, INT32_C(0))

struct hyperionnet_RawImage_table { uint8_t unused__; };

static inline size_t hyperionnet_RawImage_vec_len(hyperionnet_RawImage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hyperionnet_RawImage_table_t hyperionnet_RawImage_vec_at(hyperionnet_RawImage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hyperionnet_RawImage_table_t, vec, i, 0)
__flatbuffers_table_as_root(hyperionnet_RawImage)

__flatbuffers_define_vector_field(0, hyperionnet_RawImage, data, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_scalar_field(1, hyperionnet_RawImage, width, flatbuffers_int32, int32_t, INT32_C(-1))
__flatbuffers_define_scalar_field(2, hyperionnet_RawImage, height, flatbuffers_int32, int32_t, INT32_C(-1))
typedef uint8_t hyperionnet_ImageType_union_type_t;
__flatbuffers_define_integer_type(hyperionnet_ImageType, hyperionnet_ImageType_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, hyperionnet_ImageType)
#define hyperionnet_ImageType_NONE ((hyperionnet_ImageType_union_type_t)UINT8_C(0))
#define hyperionnet_ImageType_RawImage ((hyperionnet_ImageType_union_type_t)UINT8_C(1))

static inline const char *hyperionnet_ImageType_type_name(hyperionnet_ImageType_union_type_t type)
{
    switch (type) {
    case hyperionnet_ImageType_NONE: return "NONE";
    case hyperionnet_ImageType_RawImage: return "RawImage";
    default: return "";
    }
}

static inline int hyperionnet_ImageType_is_known_type(hyperionnet_ImageType_union_type_t type)
{
    switch (type) {
    case hyperionnet_ImageType_NONE: return 1;
    case hyperionnet_ImageType_RawImage: return 1;
    default: return 0;
    }
}


struct hyperionnet_Image_table { uint8_t unused__; };

static inline size_t hyperionnet_Image_vec_len(hyperionnet_Image_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hyperionnet_Image_table_t hyperionnet_Image_vec_at(hyperionnet_Image_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hyperionnet_Image_table_t, vec, i, 0)
__flatbuffers_table_as_root(hyperionnet_Image)

__flatbuffers_define_union_field(flatbuffers_, 1, hyperionnet_Image, data, hyperionnet_ImageType, 1)
__flatbuffers_define_scalar_field(2, hyperionnet_Image, duration, flatbuffers_int32, int32_t, INT32_C(-1))

struct hyperionnet_Clear_table { uint8_t unused__; };

static inline size_t hyperionnet_Clear_vec_len(hyperionnet_Clear_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hyperionnet_Clear_table_t hyperionnet_Clear_vec_at(hyperionnet_Clear_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hyperionnet_Clear_table_t, vec, i, 0)
__flatbuffers_table_as_root(hyperionnet_Clear)

__flatbuffers_define_scalar_field(0, hyperionnet_Clear, priority, flatbuffers_int32, int32_t, INT32_C(0))

struct hyperionnet_Color_table { uint8_t unused__; };

static inline size_t hyperionnet_Color_vec_len(hyperionnet_Color_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hyperionnet_Color_table_t hyperionnet_Color_vec_at(hyperionnet_Color_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hyperionnet_Color_table_t, vec, i, 0)
__flatbuffers_table_as_root(hyperionnet_Color)

__flatbuffers_define_scalar_field(0, hyperionnet_Color, data, flatbuffers_int32, int32_t, INT32_C(-1))
__flatbuffers_define_scalar_field(1, hyperionnet_Color, duration, flatbuffers_int32, int32_t, INT32_C(-1))
typedef uint8_t hyperionnet_Command_union_type_t;
__flatbuffers_define_integer_type(hyperionnet_Command, hyperionnet_Command_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, hyperionnet_Command)
#define hyperionnet_Command_NONE ((hyperionnet_Command_union_type_t)UINT8_C(0))
#define hyperionnet_Command_Color ((hyperionnet_Command_union_type_t)UINT8_C(1))
#define hyperionnet_Command_Image ((hyperionnet_Command_union_type_t)UINT8_C(2))
#define hyperionnet_Command_Clear ((hyperionnet_Command_union_type_t)UINT8_C(3))
#define hyperionnet_Command_Register ((hyperionnet_Command_union_type_t)UINT8_C(4))

static inline const char *hyperionnet_Command_type_name(hyperionnet_Command_union_type_t type)
{
    switch (type) {
    case hyperionnet_Command_NONE: return "NONE";
    case hyperionnet_Command_Color: return "Color";
    case hyperionnet_Command_Image: return "Image";
    case hyperionnet_Command_Clear: return "Clear";
    case hyperionnet_Command_Register: return "Register";
    default: return "";
    }
}

static inline int hyperionnet_Command_is_known_type(hyperionnet_Command_union_type_t type)
{
    switch (type) {
    case hyperionnet_Command_NONE: return 1;
    case hyperionnet_Command_Color: return 1;
    case hyperionnet_Command_Image: return 1;
    case hyperionnet_Command_Clear: return 1;
    case hyperionnet_Command_Register: return 1;
    default: return 0;
    }
}


struct hyperionnet_Request_table { uint8_t unused__; };

static inline size_t hyperionnet_Request_vec_len(hyperionnet_Request_vec_t vec)
__flatbuffers_vec_len(vec)
static inline hyperionnet_Request_table_t hyperionnet_Request_vec_at(hyperionnet_Request_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(hyperionnet_Request_table_t, vec, i, 0)
__flatbuffers_table_as_root(hyperionnet_Request)

__flatbuffers_define_union_field(flatbuffers_, 1, hyperionnet_Request, command, hyperionnet_Command, 1)


#include "flatcc/flatcc_epilogue.h"
#endif /* HYPERION_REQUEST_READER_H */
